### PR TITLE
Text update to API doc Explanation

### LINKED ISSUE #579: Changes to explaination of imap-data-access in Data Access API docs
Currently the [API docs](https://imap-processing.readthedocs.io/en/latest/data-access-api/index.html) mention that the `imap-data-access` repo serves as a command-line utility for the API. However, we should move this text to the top of the page and make it more clear in the docs that this is the _preferred_ way to use the API. The way it is currently explained in the docs, and where it is placed in the docs, makes it kind of seem like an afterthought. 

The page is found [here](https://github.com/IMAP-Science-Operations-Center/imap_processing/blob/dev/docs/source/data-access-api/index.rst) in the repo.

### PR DESCRIPTION
**Pull request by daralynnrhode**
# Student Issue 579 API Document Text Update

## Overview

Updated the text included in index.rst for the API. 

## New Dependencies

None

## New Files

None

## Deleted Files

None

## Updated Files

- Index.rst for data-access-api
   - Rearranged explanation to convey the idea more concisely.
   - Added one sentence to show that the imap-data-access is the preferred way to utilize the API.

## Testing

None

### CODE REVIEW

**Review by greglucas — APPROVED** [review]
Nice!

Also as an FYI: If you put the text "closes #XXX" in the PR description text it will automatically link the issue for you and close it once this PR is merged.

**Review by bourque — APPROVED** [review]
Great work on quickly learning our git workflow!

**Review by maxinelasp — APPROVED** [review]
Nice, looks good!

**Comment by bourque** [comment]
@all-contributors please add @daralynnrhode for code and documentation!

**Pull request merged**
