### PR TITLE
DOC: Add autosummary templates and update docstrings for code

### PR DESCRIPTION
**Pull request by greglucas**
# Change Summary
This adds the ability to autosummarize the code modules we are using for easier API documentation. We also follow numpydoc conventions, so we now install that to get nicer formatting of the API docs.

## New Dependencies
numpydoc

## New Files
- autosummary.rst
   - This adds all the autuosummarized modules to toctrees so that they can be referenced elsewhere. Otherwise we get warnings in the doc builds.

## Updated Files
Updated docstrings for several of the modules to follow numpydoc conventions and render better.

## Testing
I've added `SPHINXOPTS="-W --keep-going -n"` to our documentation build so that we will get warnings/failures when documentation warnings crop up and we can flag them right away.

### CODE REVIEW

**Review by bourque — APPROVED** [review]
Thanks @greglucas, looks good to me.  I built this locally and it looks good in the HTML too.

**Comment by greglucas** [comment]
> Thanks @greglucas, looks good to me. I built this locally and it looks good in the HTML too.

FYI, you don't even need to build locally anymore! The read the docs link in the checks contains our built PRs that you can just click around in 🎉 

image

**Review by maxinelasp — APPROVED** [review]
I like it!

**Comment by greglucas** [comment]
Merging to get CI working again.

**Pull request merged**
