### PR TITLE
Ruff docs

### PR DESCRIPTION
**Pull request by greglucas**
# Change Summary

NOTE: This is a proposal. Do we want to follow all of these conventions? Are some of these too annoying and will make too much noise and therefore we should ignore them? I went through and made the changes I thought made sense for now and they didn't seem _too_ bad, and it is better to start these checks sooner rather than later IMO.

## Overview

Add numpydoc conventions to our continuous integration setup to
start enforcing documentation standards.

Have chosen to ignore module-level and package-level docstrings
for now. We can add those rules later if we want. We also ignore
these for the tools and tests directory, which can be added later
as well if we think they are needed.

## Updated Files
Many, I updated the docstrings to meet the ruff enforced standards.

## Testing
Ignored docstrings in our tests directory.

### CODE REVIEW

**Review by maxinelasp — APPROVED** [review]
I think the changes you had to make show that we are already using this basic style in our documentation. I think it's a good thing to add to the pre commit.

**Review by bourque — APPROVED** [review]
I like all of these changes, and I am for enforcing these moving forward.

I think I would also be good with module-level enforcement too.

**Review by sdhoyt — APPROVED** [review]
I agree. I think it would be good to add this to the checks.

**Comment by greglucas** [comment]
Since we seem to have a consensus on this. I'm going to merge because there are going to be minor merge conflicts coming up with all the PRs and I'd like to push those on to everyone else so you all can update the docstrings in your own words and I don't have to infer what you want!

**Pull request merged**
