### PR TITLE
DOC: Update sphinx references

### PR DESCRIPTION
**Pull request by greglucas**
# Change Summary

As I was going through #85 I noticed that there were unrelated doc build warnings: https://github.com/IMAP-Science-Operations-Center/imap_processing/actions/runs/6015856727/job/16318618164#step:5:43
so this goes through and fixes up the minor warnings.

There was a duplicate explicit named reference, so change those to implicit names with "__" for the links.
The poetry-link reference needed to be swapped and go within the brackets.

## New Dependencies

I updated the pre-commit versions with `pre-commit autoupdate` and then committed that file. There was a version mismatch in the `poetry.lock` file (pre-commit saying it was 1.5.0 that it wanted, but the lock file having 1.5.1). I am not sure how that happened, but perhaps because someone made the lock file through their local poetry venv rather than the pre-commit venv? I wonder if there is a way to make sure those are consistent or that we can guarantee the consistency somehow there...

Now, of course, we updated to 1.6.0 within pre-commit and it is OK with the 1.5.1 creation path! I think there was an extra YAML dependency added in with version conflicts, so apparently now the poetry.lock check is happy 🤷

### CODE REVIEW

**Comment by maxinelasp** [comment]
The lock file may be inconsistent because the precommit uses the `--no-update` flag. It presumably saw that the version was up to date and didn't update again because it wasn't necessary. That's my guess!

**Review by maxinelasp — APPROVED** [review]

**Comment by greglucas** [comment]
> The lock file may be inconsistent because the precommit uses the --no-update flag. It presumably saw that the version was up to date and didn't update again because it wasn't necessary. That's my guess!

Yeah, I think it does have to do with the way we are updating things locally vs pre-commit.

My guess is that it is because I don't have poetry in my main environment and I rely on the specific poetry version within pre-commit's environment (separate from my work environment). But, you all have poetry available locally so if you manually run `poetry lock` that will use the _local_ poetry which may not be pinned to the exact same version as the pre-commit poetry version. (That is why there was a "this was generated with 1.5.1" within the poetry lock file when pre-commit is pinned to 1.5.0

**Comment by maxinelasp** [comment]
I looked into keeping poetry at one version, but I couldn't find a way to specify the _poetry_ version in pyproject.toml (turns out googling "poetry specify version" does not get you helpful results, and I don't know what else to search for, lol)

**Review by bourque — APPROVED** [review]
LGTM

**Pull request merged**
