### PR TITLE
TST: Add coverage to testing pipeline

### PR DESCRIPTION
**Pull request by greglucas**
# Change Summary

This adds code coverage checks to our testing pipeline. I'm not sure if codecov is currently running on the org, or if we need to add it to this repo explicitly. We'll see once the PR is opened.

## New Dependencies
`pytest-cov` to run code coverage through pytest

### CODE REVIEW

**Comment by maxinelasp** [comment]
Does this only run code coverage in the testing pipeline? I don't generally love code coverage as any kind of commit blocker, but just having a report and a percentage goal to aim for is alright with me. Is there some easier way to view the report than that link in the testing details page?

**Comment by greglucas** [comment]
> Does this only run code coverage in the testing pipeline?

Yes, it only runs it in CI. We could add it locally as well by setting default options for when we invoke `pytest`, but I generally invoke it manually if I'm curious: `pytest --cov`

> I don't generally love code coverage as any kind of commit blocker, but just having a report and a percentage goal to aim for is alright with me.

I agree that it being a blocker is generally not good. However, I think it is quite valuable for reviewers to know whether the PR has added the proper tests for their portion of the code. I like the idea of adding a percentage target to your PR review guidelines and leaving these as "status" but not blockers for merging. (I do think we should strive for 100% coverage on our algorithms if possible though...)

>  Is there some easier way to view the report than that link in the testing details page?

We have it on our sds-data-manager repo, see for example this PR: https://github.com/IMAP-Science-Operations-Center/sds-data-manager/pull/151 If you click on the show checks, then you'll see the codecov information that you can click and link out to.

**Comment by maxinelasp** [comment]
Ok, that all sounds good!

**Review by maxinelasp — APPROVED** [review]

**Review by sdhoyt — APPROVED** [review]

**Comment by greglucas** [comment]
We may need to tweak some of the settings for what is allowed/expected from the codecov, but I think we can do that once we see how this is behaving on other PRs.

**Pull request merged**
